name: CD Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ekzis/diamond-crm:latest .

      # 3️⃣ Login to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 4️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ekzis/diamond-crm:latest

      - name: Copy deploy script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: 'scripts/deploy-blue-green.sh'
          target: '/tmp/'

      - name: Run deploy script
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            chmod +x /tmp/scripts/deploy-blue-green.sh
            /tmp/scripts/deploy-blue-green.sh
            rm -f /tmp/scripts/deploy-blue-green.sh
