name: CI/CD

on:
  push:
  pull_request:

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile || npm ci

      - name: Lint Backend
        working-directory: ./backend
        run: yarn lint

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile || npm ci

      - name: Lint Frontend
        working-directory: ./frontend
        run: yarn lint

  build-docker:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test-backend
      - test-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ekzis/diamond-crm:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ekzis/diamond-crm:latest

  deploy-stage:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy rollout script to stage
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: 'scripts/stage_deployer.sh'
          target: '/tmp/'

      - name: Run rollout script on stage
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            chmod +x /tmp/scripts/stage_deployer.sh
            /tmp/scripts/stage_deployer.sh

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment:
      name: production
      url: https://ahahlol.space
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy rollout script to production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: 'scripts/deploy-blue-green.sh,scripts/production_deployer.sh'
          target: '/tmp/'

      - name: Run rollout script on production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            chmod +x /tmp/scripts/production_deployer.sh
            chmod +x /tmp/scripts/deploy-blue-green.sh
            /tmp/scripts/production_deployer.sh
